# Generated by Django 2.1.3 on 2018-11-12 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Kanoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('FoundationDate', models.IntegerField(unique_for_year=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(blank=True, max_length=100)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('isValid', models.BooleanField(default=False)),
                ('Kanoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Kanoon')),
                ('Username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=30)),
                ('LastName', models.CharField(blank=True, max_length=30)),
                ('NickName', models.CharField(blank=True, max_length=30)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Group', models.ManyToManyField(to='api.Group')),
                ('Kanoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Kanoon')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='Kanoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Kanoon'),
        ),
    ]
