# Generated by Django 2.1.3 on 2018-11-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanoon',
            name='FoundationDate',
            field=models.IntegerField(),
        ),
    ]
