# Generated by Django 2.1.3 on 2018-11-12 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20181112_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Description', models.TextField()),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Group', models.ManyToManyField(to='api.Group')),
                ('Kanoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Kanoon')),
                ('Members', models.ManyToManyField(to='api.Member')),
            ],
        ),
    ]
