# Generated by Django 2.1.3 on 2018-11-20 23:53

import awesome_avatar.fields
from django.db import migrations, models
import django_jalali.db.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='kanoon',
            name='Logo',
            field=awesome_avatar.fields.AvatarField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AddField(
            model_name='leader',
            name='Avatar',
            field=awesome_avatar.fields.AvatarField(blank=True, null=True, upload_to='Leaders'),
        ),
        migrations.AddField(
            model_name='leader',
            name='Email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='Avatar',
            field=awesome_avatar.fields.AvatarField(blank=True, null=True, upload_to='Members'),
        ),
        migrations.AddField(
            model_name='member',
            name='BrithDate',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='Email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
        migrations.AlterField(
            model_name='member',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
